### ISSUE TITLE
JavaScript parser for Microsoft BASIC ?

### ISSUE THREAD

**Issue by beurkinger** [jdan/basic2020#1]

**Comment by jdan** [comment]
It's a BASIC-like language that I'm making up as I go along :) Wanted to see if it's enjoyable to make web apps with this. Would be cool for a generation of programmers to learn with BASIC again.

**Comment by beurkinger** [comment]
Will... will it include the GOTO statement ? In my mind it was a staple of the authentic BASIC programming experience ;)

I think it's a very interesting project, don't hesitate to message me if you ever need help with it, recently I've been meaning to work on something a little more "abstract", and also to collaborate on open-source projects.

Anyway, good luck !

**Comment by jdan** [comment]
Maybe :) Dunno! && will do, currently just exploring.
